project_id = "bwxbhircezyhwekdngdk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[edge_runtime]
policy = "per_worker"
inspector_port = 8083

[functions.article-service]
verify_jwt = true

[functions.banner-service]
verify_jwt = true

[functions.audit-service]
verify_jwt = false

[functions.media-service]
verify_jwt = true

[functions.content-extraction-service]
verify_jwt = false

[functions.ai-image-generation-service]
verify_jwt = false

[functions.ai-rewriter-service]
verify_jwt = false

[functions.ai-article-generator-service]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.user-service]
verify_jwt = true

[functions.public-config]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.ai-config-tester]
verify_jwt = true

[functions.groq-config]
verify_jwt = true

[functions.user-profiles-service]
verify_jwt = true

[functions.enhanced-user-service]
verify_jwt = true